### ISSUE TITLE
AttributeError: 'Namespace' object has no attribute 'certbot_heroku:heroku_map'

### ISSUE THREAD

**Issue by oluwatayo** [gboudreau/certbot-heroku#9]
I encounter this error in step 3(Usage)
Traceback (most recent call last):
  File "/usr/local/bin/certbot", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/certbot/main.py", line 1240, in main
    return config.func(config, plugins)
  File "/usr/local/lib/python2.7/dist-packages/certbot/main.py", line 1120, in certonly
    lineage = _get_and_save_cert(le_client, config, domains, certname, lineage)
  File "/usr/local/lib/python2.7/dist-packages/certbot/main.py", line 118, in _get_and_save_cert
    lineage = le_client.obtain_and_enroll_certificate(domains, certname)
  File "/usr/local/lib/python2.7/dist-packages/certbot/client.py", line 375, in obtain_and_enroll_certificate
    self.config)
  File "/usr/local/lib/python2.7/dist-packages/certbot/storage.py", line 1064, in new_lineage
    values = relevant_values(vars(cli_config.namespace))
  File "/usr/local/lib/python2.7/dist-packages/certbot/storage.py", line 244, in relevant_values
    for option, value in six.iteritems(all_values)
  File "/usr/local/lib/python2.7/dist-packages/certbot/storage.py", line 245, in <genexpr>
    if _relevant(option) and cli.option_was_set(option, value))
  File "/usr/local/lib/python2.7/dist-packages/certbot/cli.py", line 250, in option_was_set
    return set_by_cli(option) or not has_default_value(option, value)
  File "/usr/local/lib/python2.7/dist-packages/certbot/cli.py", line 212, in set_by_cli
    if not isinstance(getattr(detector, var), _Default):
AttributeError: 'Namespace' object has no attribute 'certbot_heroku:heroku_map'
2018-01-29 12:05:01,170:ERROR:certbot.log:An unexpected error occurred:

**Comment by nomaed** [comment]
Getting the same.

MacOS 10.13.6
certbot 0.27.1

Log:

```
2018-09-19 21:05:21,704:DEBUG:certbot.storage:Archive directory /etc/letsencrypt/archive/[*******].herokuapp.com-0002 and live directory /etc/letsencrypt/live/[*******].herokuapp.com-0002 created.
2018-09-19 21:05:21,705:DEBUG:certbot.storage:Writing certificate to /etc/letsencrypt/live/[*******].herokuapp.com-0002/cert.pem.
2018-09-19 21:05:21,706:DEBUG:certbot.storage:Writing private key to /etc/letsencrypt/live/[*******].herokuapp.com-0002/privkey.pem.
2018-09-19 21:05:21,706:DEBUG:certbot.storage:Writing chain to /etc/letsencrypt/live/[*******].herokuapp.com-0002/chain.pem.
2018-09-19 21:05:21,706:DEBUG:certbot.storage:Writing full chain to /etc/letsencrypt/live/[*******].herokuapp.com-0002/fullchain.pem.
2018-09-19 21:05:21,707:DEBUG:certbot.storage:Writing README to /etc/letsencrypt/live/[*******].herokuapp.com-0002/README.
2018-09-19 21:05:21,796:DEBUG:certbot.plugins.selection:Requested authenticator certbot-heroku:heroku and installer <certbot.cli._Default object at 0x10e27f390>
2018-09-19 21:05:21,797:DEBUG:certbot.cli:Var certbot_heroku:heroku_app=[*******] (set by user).
2018-09-19 21:05:21,936:DEBUG:certbot.log:Exiting abnormally:
Traceback (most recent call last):
  File "/usr/local/bin/certbot", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/certbot/main.py", line 1364, in main
    return config.func(config, plugins)
  File "/usr/local/lib/python2.7/site-packages/certbot/main.py", line 1254, in certonly
    lineage = _get_and_save_cert(le_client, config, domains, certname, lineage)
  File "/usr/local/lib/python2.7/site-packages/certbot/main.py", line 120, in _get_and_save_cert
    lineage = le_client.obtain_and_enroll_certificate(domains, certname)
  File "/usr/local/lib/python2.7/site-packages/certbot/client.py", line 409, in obtain_and_enroll_certificate
    self.config)
  File "/usr/local/lib/python2.7/site-packages/certbot/storage.py", line 1068, in new_lineage
    values = relevant_values(vars(cli_config.namespace))
  File "/usr/local/lib/python2.7/site-packages/certbot/storage.py", line 244, in relevant_values
    for option, value in six.iteritems(all_values)
  File "/usr/local/lib/python2.7/site-packages/certbot/storage.py", line 245, in <genexpr>
    if _relevant(option) and cli.option_was_set(option, value))
  File "/usr/local/lib/python2.7/site-packages/certbot/cli.py", line 263, in option_was_set
    return set_by_cli(option) or not has_default_value(option, value)
  File "/usr/local/lib/python2.7/site-packages/certbot/cli.py", line 217, in set_by_cli
    if not isinstance(getattr(detector, var), _Default):
AttributeError: 'Namespace' object has no attribute 'certbot_heroku:heroku_map'
2018-09-19 21:05:21,938:ERROR:certbot.log:An unexpected error occurred:
```
